### ISSUE TITLE
Meta issue: revisions, latency, backfill, nowcasting etc

### ISSUE THREAD

**Issue by dsweber2** [cmu-delphi/epiprocess#486]
A list of issues/PRs and a place to keep track of ideas related to revision analysis:

- [ ] - location in the docs with a todo on detailed revision analysis https://github.com/cmu-delphi/epiprocess/issues/432
- [ ] - #205 should just use basic stuff like nominal latency
- [ ] - "We should try to have chapters/functions that create some figures similar to some of those in Sarabeth's reports, though Sarabeth's reports are not public." - @lcbrooks 
- [ ] - Revision MAPE curve part of #355
- [ ] - #375  Dedicated lag extraction function (or maybe data structure?) --- not quite analysis, but useful for backcasting.
- [ ] - latency function from [this vignette](https://github.com/cmu-delphi/epiprocess/blob/ba546960b03a17cf5c6d9db1459c202b13de86ba/vignettes/latency_revision_stats.Rmd). Broad array of definitions, some are buggy (but noted that they are)
